version: "3.9"

services:
 api:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: picpay-api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www
    networks:
      - picpay-network
    depends_on:
      - mysql

 mysql:
    image: mysql:5.7
    container_name: picpay-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --init-file /tmp/init.sql
    ports:
      - 3399:3306
    volumes:
      - ./docker/mysql/init.sql:/tmp/init.sql
      - ./docker/mysql/db:/var/lib/mysql
    networks:
      - picpay-network

 nginx:
    image: nginx:1.23.1-alpine
    container_name: picpay-nginx
    ports:
      - 8099:80
    volumes:
      - ./api:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - picpay-network
    depends_on:
      - api

networks:
  picpay-network:
    driver: bridge